### ISSUE TITLE
Add link to target file

### ISSUE THREAD

**Issue by zimt28** [phoenix-diff/phoenix-diff#171]
_Feature request:_ Add a link to the target file on GitHub so it's easier to copy big changes

**Comment by aaronrenner** [comment]
That makes a lot of sense. Once I finish up the new diff viewer, that should be straight forward to add.

In the meantime, all of the raw files are stored here so you can copy what you need: https://github.com/phoenix-diff/phoenix-diff/tree/master/priv/data/sample-app
